"""PostgreSQL role-separation SQL templates for production deployments."""

from __future__ import annotations

import re
from dataclasses import astuple, dataclass


@dataclass(frozen=True, slots=True)
class PostgresRoleNames:
    owner: str = "prodkit_owner"
    migrator: str = "prodkit_migrator"
    runtime: str = "prodkit_runtime"
    read_only: str = "prodkit_readonly"
    support: str = "prodkit_support"

    def validated(self) -> PostgresRoleNames:
        for value in astuple(self):
            _identifier(value)
        if len(set(astuple(self))) != 5:
            raise ValueError("database role names must be distinct")
        return self


def render_role_bootstrap_sql(
    *,
    database: str,
    schema: str = "public",
    roles: PostgresRoleNames | None = None,
) -> str:
    """Render role membership and default-privilege bootstrap SQL.

    The migrator is intentionally ``NOINHERIT``. Alembic should connect as the
    migrator and ``SET ROLE`` to the owner via
    ``PRODKIT_STORAGE_MIGRATION_OWNER_ROLE`` before creating schema objects.
    Passwords and login grants are intentionally omitted.
    """

    roles = (roles or PostgresRoleNames()).validated()
    database = _identifier(database)
    schema = _identifier(schema)
    declarations = "\n".join(
        _role_block(
            role,
            login=role in {
                roles.migrator,
                roles.runtime,
                roles.read_only,
                roles.support,
            },
        )
        for role in astuple(roles)
    )
    return f"""-- Generated by prodkit-storage. Review before execution.
{declarations}

ALTER DATABASE {database} OWNER TO {roles.owner};
GRANT CONNECT ON DATABASE {database}
TO {roles.migrator}, {roles.runtime}, {roles.read_only}, {roles.support};

ALTER SCHEMA {schema} OWNER TO {roles.owner};
GRANT USAGE ON SCHEMA {schema}
TO {roles.migrator}, {roles.runtime}, {roles.read_only}, {roles.support};

-- NOINHERIT keeps migration privileges explicit; Alembic must SET ROLE.
GRANT {roles.owner} TO {roles.migrator};
ALTER ROLE {roles.runtime} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER ROLE {roles.read_only} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER ROLE {roles.support} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;

ALTER DEFAULT PRIVILEGES FOR ROLE {roles.owner} IN SCHEMA {schema}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {roles.runtime};
ALTER DEFAULT PRIVILEGES FOR ROLE {roles.owner} IN SCHEMA {schema}
  GRANT SELECT ON TABLES TO {roles.read_only}, {roles.support};
ALTER DEFAULT PRIVILEGES FOR ROLE {roles.owner} IN SCHEMA {schema}
  GRANT USAGE, SELECT ON SEQUENCES TO {roles.runtime};
"""


def render_post_migration_grants_sql(
    *,
    schema: str = "public",
    roles: PostgresRoleNames | None = None,
) -> str:
    """Render grants for existing objects after a migration completes.

    Audit events are append-only for the runtime role. Outbox rows are mutable
    for dispatch state transitions but runtime deletion is withheld so cleanup
    can be delegated to a dedicated retention/maintenance workflow.
    """

    roles = (roles or PostgresRoleNames()).validated()
    schema = _identifier(schema)
    return f"""-- Generated by prodkit-storage. Apply after migrations.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {schema} TO {roles.runtime};
GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO {roles.read_only}, {roles.support};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA {schema} TO {roles.runtime};

-- Shared audit table: runtime may append but cannot read payload/history or mutate rows.
REVOKE SELECT, UPDATE, DELETE ON TABLE {schema}.storage_audit_events FROM {roles.runtime};
GRANT INSERT ON TABLE {schema}.storage_audit_events TO {roles.runtime};
-- SQLAlchemy fetches the server-generated timestamp with INSERT ... RETURNING.
-- PostgreSQL requires SELECT on each column referenced by RETURNING, so expose
-- only this non-payload column rather than granting table-wide audit reads.
GRANT SELECT (occurred_at) ON TABLE {schema}.storage_audit_events TO {roles.runtime};

-- Shared outbox table: publishing updates are allowed; retention deletion is separate.
REVOKE DELETE ON TABLE {schema}.storage_outbox_events FROM {roles.runtime};
GRANT SELECT, INSERT, UPDATE ON TABLE {schema}.storage_outbox_events TO {roles.runtime};
"""


def _role_block(role: str, *, login: bool) -> str:
    login_sql = "LOGIN" if login else "NOLOGIN"
    return f"""DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
    CREATE ROLE {role} {login_sql} NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;"""


def _identifier(value: str) -> str:
    if re.fullmatch(r"[a-z_][a-z0-9_]*", value) is None:
        raise ValueError(f"invalid PostgreSQL identifier: {value!r}")
    return value


__all__ = [
    "PostgresRoleNames",
    "render_post_migration_grants_sql",
    "render_role_bootstrap_sql",
]
