"""PostgreSQL role-separation SQL templates for production deployments."""

from __future__ import annotations

import re
from dataclasses import astuple, dataclass


@dataclass(frozen=True, slots=True)
class PostgresRoleNames:
    owner: str = "prodkit_owner"
    migrator: str = "prodkit_migrator"
    runtime: str = "prodkit_runtime"
    read_only: str = "prodkit_readonly"
    support: str = "prodkit_support"

    def validated(self) -> PostgresRoleNames:
        for value in (
            self.owner,
            self.migrator,
            self.runtime,
            self.read_only,
            self.support,
        ):
            _identifier(value)
        if len(set(astuple(self))) != 5:
            raise ValueError("database role names must be distinct")
        return self


def render_role_bootstrap_sql(
    *,
    database: str,
    schema: str = "public",
    roles: PostgresRoleNames = PostgresRoleNames(),
) -> str:
    """Render idempotent-enough role and privilege guidance SQL.

    Passwords and login grants are intentionally omitted. Provision credentials
    through the selected infrastructure secret manager.
    """

    roles = roles.validated()
    database = _identifier(database)
    schema = _identifier(schema)
    values = astuple(roles)
    declarations = "\n".join(
        _role_block(
            role,
            login=role in {
                roles.migrator,
                roles.runtime,
                roles.read_only,
                roles.support,
            },
        )
        for role in values
    )
    return f"""-- Generated by prodkit-storage. Review before execution.
{declarations}

ALTER DATABASE {database} OWNER TO {roles.owner};
GRANT CONNECT ON DATABASE {database}
TO {roles.migrator}, {roles.runtime}, {roles.read_only}, {roles.support};

ALTER SCHEMA {schema} OWNER TO {roles.owner};
GRANT USAGE, CREATE ON SCHEMA {schema} TO {roles.migrator};
GRANT USAGE ON SCHEMA {schema} TO {roles.runtime}, {roles.read_only}, {roles.support};

GRANT {roles.owner} TO {roles.migrator};
ALTER ROLE {roles.runtime} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER ROLE {roles.read_only} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER ROLE {roles.support} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;

ALTER DEFAULT PRIVILEGES FOR ROLE {roles.owner} IN SCHEMA {schema}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {roles.runtime};
ALTER DEFAULT PRIVILEGES FOR ROLE {roles.owner} IN SCHEMA {schema}
  GRANT SELECT ON TABLES TO {roles.read_only}, {roles.support};
ALTER DEFAULT PRIVILEGES FOR ROLE {roles.owner} IN SCHEMA {schema}
  GRANT USAGE, SELECT ON SEQUENCES TO {roles.runtime};

-- Existing objects need explicit grants after migrations:
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {schema} TO {roles.runtime};
GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO {roles.read_only}, {roles.support};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA {schema} TO {roles.runtime};
"""


def _role_block(role: str, *, login: bool) -> str:
    login_sql = "LOGIN" if login else "NOLOGIN"
    return f"""DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
    CREATE ROLE {role} {login_sql} NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;"""


def _identifier(value: str) -> str:
    if re.fullmatch(r"[a-z_][a-z0-9_]*", value) is None:
        raise ValueError(f"invalid PostgreSQL identifier: {value!r}")
    return value


__all__ = ["PostgresRoleNames", "render_role_bootstrap_sql"]
